services:
  dnstotp:
    build: .
    container_name: dnstotp
    restart: unless-stopped
    environment:
      DNSTOTP_ZONE: otp.deebas.com
      DNSTOTP_NS: dnsgames01.deebas.com
      RUST_LOG: debug
    ports:
      - 1053:1053/udp
    volumes:
      - ./:/data
